### ISSUE TITLE
Color input won't be focused on Safari

### ISSUE THREAD

**Issue by flourish86** [Icinga/icinga-notifications-web#110]
When I navigate through the inputs in the "Add Contact" view using Safari, the color input won't be focused.

I'm aware of the default behavior of Safari regarding input focus, that's why I'm using Option + Tab to navigate the inputs. This makes it behave like the other Browsers.

https://github.com/Icinga/icinga-notifications-web/assets/6977434/b0f88d4a-ccd6-4681-808d-dd93aa62163a

**Comment by nilmerg** [comment]
This will be gone soon.
