### ISSUE TITLE
Don't use features only available since PHP 7.3

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icinga-notifications-web#126]
I noticed in several places where `array_key_last()` is used, which is available since PHP 7.3.
https://github.com/Icinga/icinga-notifications-web/blob/e6b64c5d9509ce6c7b1ca03609995d4837f69692/application/forms/EscalationRecipientForm.php#L227

https://github.com/Icinga/icinga-notifications-web/blob/e6b64c5d9509ce6c7b1ca03609995d4837f69692/application/forms/EscalationConditionForm.php#L260

https://github.com/Icinga/icinga-notifications-web/blob/e6b64c5d9509ce6c7b1ca03609995d4837f69692/library/Notifications/Widget/EventRuleConfig.php#L86

**Comment by nilmerg** [comment]
Or we consider changing the minimum requirement. To my knowledge, no distribution we support still uses PHP 7.2

**Comment by Al2Klimov** [comment]
| | PHP |
|-|-|
| Debian 11 | 7.4 |
| Ubuntu 20.04 | 7.4 |
| SLES 12.5 | 7.4 |
| RHEL 8 | 7.2\* |

\* https://git.icinga.com/packages/icingaweb/-/jobs/534638

**Comment by nilmerg** [comment]
Well, seems we have to support 7.2 still.

**Comment by Al2Klimov** [comment]
> [@lippserd](https://github.com/lippserd) FWIW 2.0:
> 
> OS	PHP	EOL
> Debian x, 11/12	7.4/8.2	2026-08-31/2028-06-30
> Ubuntu x.04, 20/22/24	7.4/8.1/8.3	April 2025/June 2027/June 2029
> SUSE 15.x, 5/6	8/8.2	[It's complicated](https://www.suse.com/lifecycle/#suse-linux-enterprise-server-15) 😅
> RHEL x, 8/9	8.2/8.2	May 31, 2029/May 31, 2032
> Amazon Linux x, 2/2023	8.2/8.3	[It's complicated](https://github.com/Icinga/icinga-packaging/issues/314) 😅
> * I consider our current minimum of PHP 7.2 not too bad. At least far better than v5.3.
> * If we apply the stuff noted below, we can upgrade to PHP 7.4 without any delay.
> * In addition, if we wait 1.5y for some .deb OSes, we get PHP 8.

Btw., PHP 8 has return type **static**. 😎
