### ISSUE TITLE
Incident detail UI enhancements

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icinga-notifications-web#128]
Currently, the incident detail view looks as follows:
<img width="628" alt="Bildschirmfoto 2023-09-28 um 14 04 40" src="https://github.com/Icinga/icinga-notifications-web/assets/57616252/947cc5c4-84b1-4e20-bd36-8919df11c2df">

Things to be discussed and enhanced:

- The tiny source icon is rendered for each individual incident severity change (since an object belongs to a single source, it may not be necessary to display these icons).
- An incident is tied to a single object, so it is not necessary to create a separate `Object` section, since the object name is already included in the incident header.
- The `Event Source` section also only ever contains a single source, so it might be worth reconsidering this and displaying it elsewhere, for example as part of the incident header.

See also https://github.com/Icinga/icinga-notifications-web/pull/117#issuecomment-1738960007

**Comment by nilmerg** [comment]
> An incident is tied to a single object, so it is not necessary to create a separate Object section, since the object name is already included in the incident header.

This is supposed to be rendered by the source's Web integration. e.g. Icinga DB Web may show the current output there and whether the object is in downtime or not. So there's still additional information which makes it worth keeping.

**Comment by nilmerg** [comment]
@flourish86 and me discussed this and we came to these conclusions:

* The small source icon in the history is indeed redundant. Removing it from there makes sense. Though we want to add it to the list item in the header instead. The result of that should also be that the icon is visible in the primary incident list.
* As I already mentioned, the *Object* section must be kept, as integrations may provide further details there.
* The *Event Source* section will also be kept as we need a place for the label and it's not the header.
* In light of recent changes to which events are written to database, we'd like to get to a point where this is streamlined with what the incident history contains. A separate issue will follow.

**Comment by nilmerg** [comment]
> * The small source icon in the history is indeed redundant. Removing it from there makes sense. Though we want to add it to the list item in the header instead. The result of that should also be that the icon is visible in the primary incident list.

Created #161 for this.
