### ISSUE TITLE
Entry Form: Improve usability

### ISSUE THREAD

**Issue by flourish86** [Icinga/icinga-notifications-web#149]
* **Add Duplicate Button**
Add a Duplicate Button that clones the current Entry. Pressing the duplicate button should result in
a) Showing the user ask for confirmation, if they wanted to save the current changes or cancel, if applicable
b) Create a new Entry with the attributes of the given entry

* **Default Values for Start Time/End Time**
The start time field should be populated by either a) the current time or b) the time the user clicked in the calendar view
The end time should be populated with the start time plus 1 hour

* **Relabel and Relocate "Use Until Time"**
Relabel "Use Until Time" to "End Repeat". Display the field only, when an actual repeat value (values other than "Don't Repeat") are selected.

![Screenshot 2023-12-05 at 17 18 24](https://github.com/Icinga/icinga-notifications-web/assets/6977434/a0e0a296-eb84-477f-b726-eccc395dd615)

* **Enhance Preview**
Remove the "Next Occurrences" element and add a preview button that renders the current changes to the calendar viewport. For this to be effective, the entry form has to be persistent, when the user changes the view mode of the calendar.

* **Streamline "Repeat" Option**
Merge Repeat Field and "Custom Frequency", so there's only one field left. Remove the "Regular" options.

![Screenshot 2023-12-05 at 16 44 18](https://github.com/Icinga/icinga-notifications-web/assets/6977434/7c9bd88d-a837-4b74-a59d-66d4951f4501)

# Design
* It's more space efficient to align the inputs and labels horizontally. 

More mockups to follow …

**Comment by nilmerg** [comment]
Obsolete once #183 is finished.
