### ISSUE TITLE
Channel Form: Unexpected default value behavior as placeholder

### ISSUE THREAD

**Issue by oxzi** [Icinga/icinga-notifications-web#154]
Describing a channel holding a configuration option with a non empty default field results in this default being rendered as the input's placeholder (`<input placeholder="…">`). However, when creating or editing this channel through web, this placeholder value will not be reflected in the database and is not used as a default.

As a concrete example, let's start with the following Go snippet:
```go
func (ch *Webhook) GetInfo() *plugin.Info {
	elements := []*plugin.ConfigOption{
		// [ . . . ]
		{
			Name: "request_body_template",
			Type: "string",
			Label: map[string]string{
				"en_US": "Request Body Template",
				"de_DE": "Anfragedaten-Template",
			},
			Help: map[string]string{
				"en_US": "Go template applied to the current plugin.NotificationRequest to create an request body.",
				"de_DE": "Go-Template über das zu verarbeitende plugin.NotificationRequest zum Erzeugen der mitgesendeten Anfragedaten.",
			},
			// Default as a minimal working example to send a JSON object.
			Default: `{"id": {{.Incident.Id}}, "type": "{{.Event.Type}}", "name": "{{.Object.Name}}", "severity": "{{.Incident.Severity}}", "url": "{{.Incident.Url}}"}`,
		},
	}

	// [ . . . ]
}
```

This results in the following `available_channel_type` entry:
```
notifications=# select config_attrs from available_channel_type where type = 'webhook';
-[ RECORD 1 ]-
config_attrs | [{…},{"name":"request_body_template","type":"string","label":{"de_DE":"Anfragedaten-Template","en_US":"Request Body Template"},"help":{"de_DE":"Go-Template über das zu verarbeitende plugin.NotificationRequest zum Erzeugen der mitgesendeten Anfragedaten.","en_US":"Go template applied to the current plugin.NotificationRequest to create an request body."},"default":"{\"id\": {{.Incident.Id}}, \"type\": \"{{.Event.Type}}\", \"name\": \"{{.Object.Name}}\", \"severity\": \"{{.Incident.Severity}}\", \"url\": \"{{.Incident.Url}}\"}","min":null,"max":null}]
```

Within the web, the following output will be generated:
![2024-01-12-100008_871x316_scrot](https://github.com/Icinga/icinga-notifications-web/assets/8402811/54bbdc24-45f6-48b3-8082-3c28856864bf)

```html
<div class="control-group">
  <div class="control-label-group">
    <label>Request Body Template</label>
  </div>
  <input placeholder="{&quot;id&quot;: {{.Incident.Id}}, &quot;type&quot;: &quot;{{.Event.Type}}&quot;, &quot;name&quot;: &quot;{{.Object.Name}}&quot;, &quot;severity&quot;: &quot;{{.Incident.Severity}}&quot;, &quot;url&quot;: &quot;{{.Incident.Url}}&quot;}" name="config[request_body_template]" type="text">
  <i class="icon fa-info-circle control-info fa" role="image" title="Go template applied to the current plugin.NotificationRequest to create an request body."></i>
</div>
```

However, when now saving this entry with the placeholder value, it will be written as `null` to the database:
```
notifications=# select * from channel;
-[ RECORD 1 ]-------------------------------------------------------------------------------------------------------
id     | 1
name   | web
type   | webhook
config | {"method":"POST","url_template":"http:\/\/http-echo:8000\/{{.Incident.Id}}\/","request_body_template":null}
```

I would expect a default named field to create a default value which will be used when no other value was entered.

**Comment by nilmerg** [comment]
The reason for this behavior is that a default may change. If a default is stored that way, it never changes automatically. If the default is not applied by the channel plugin, this needs to be fixed.

**Comment by oxzi** [comment]
> The reason for this behavior is that a default may change. If a default is stored that way, it never changes automatically. If the default is not applied by the channel plugin, this needs to be fixed.

Fair enough. But then it should be reflected in the database that the default value should be used. This would also bring up the question how to distinct an empty or `null` value from the wish to use the default.

**Comment by nilmerg** [comment]
Usually, a non existing value for a config option means to use the default. In this case, `NULL`. But yeah, it is currently not possible to store e.g. the empty string. We could of course change this, so that the default is not a placeholder, but is just not stored if not adjusted.

**Comment by oxzi** [comment]
As I just stumbled about this again: configuring a `Default` results in populating the `input`'s `placeholder` field, but one has to manually type the value again in the web dialog when `Required: true`.

This is a bit frustrating, as I am unable to catch this on the backend by replacing an empty value to the configured default because the web dialog forbids submitting an empty form. However, when I starts typing, the shown `placeholder` disappears.

![2024-04-18-124433_1033x414_scrot](https://github.com/Icinga/icinga-notifications-web/assets/8402811/103b1d82-0efd-4629-8a19-80add648e455)

**Comment by nilmerg** [comment]
Have you seen https://github.com/Icinga/icinga-notifications/issues/172?

**Comment by oxzi** [comment]
> Have you seen [Icinga/icinga-notifications#172](https://github.com/Icinga/icinga-notifications/issues/172)?

Now I've seen it. It kinda addresses this very issue.

**Comment by oxzi** [comment]
Thanks for working on this issue. However, it seems like this has now another bug. If one sets the default value - even when changing from another string back to the default value -, the key value pair gets removed from the config JSON struct, resulting in it being unavailable.

It would be possible to set the default in the daemon (or the plugin, to be even more correct), but this would require allowing to differentiate between a valid empty string/empty value and a NULL value.

**Comment by oxzi** [comment]
I wanted to point this out again because I am not sure if it was understood correctly.

Using the email channel plugin as an example, the SMTP user defaults to "user@example.com". If I clear this field in the web UI, - i.e., because I explicitly want an empty SMTP User due to no SMTP in-band authentication - the logic will show the "default" value in the web UI while having an unset value in the database.

So if the daemon (or the channel plugin) now replaces unset values with the default value, I would end up with an invalid configuration.

I would suggest filling the web UI with the defaults when creating a new channel entry, but not working with the defaults after that.

**Comment by nilmerg** [comment]
Aye, though, what does the daemon prefer? `NULL` or the empty string in case of a default that was cleared?

**Comment by nilmerg** [comment]
Don.e

**Comment by yhabteab** [comment]
Apart from that, saving this channel configuration generates the following json in the database and completely misses the `response_status_codes` field.

<img width="623" alt="Bildschirmfoto 2024-05-28 um 17 01 17" src="https://github.com/Icinga/icinga-notifications-web/assets/57616252/4724bd63-0dcb-4c35-a20f-50beb939e667">


**Database:**
```bash
{"method":null,"url_template":"{\"id\": {{.Incident.Id}}, \"type\": \"{{.Event.Type}}\", \"name\": \"{{.Object.Name}}\", \"severity\": \"{{.Incident.Severity}}\", \"url\": \"{{.Incident.Url}}\"}","request_body_template":null}
```

**Comment by raviks789** [comment]
> You are right! I forgot to rebuild my executable channels! But when I change the channel type to `webhook`, I immediately get a validation error for the **URL Template** field that says `This field is required`.

I am pretty sure this is expected. As it happens due to partial validation of the fieldset, where it is not yet assembled.
