### ISSUE TITLE
Events and Incident History Improvements

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-notifications-web#157]
Recent changes to icinga-notifications made internal events appear in the events listing. They are currently shown like this:

## Events
![image](https://github.com/Icinga/icinga-notifications-web/assets/16668527/73eb8bcf-9e5c-4963-9cc9-9c27eb853bb8)

### Prerequisites

It is currently not possible to differentiate between internal events. The daemon needs to write them to the database in a way, this can happen: https://github.com/Icinga/icinga-notifications/issues/162

Until the daemon is updated, the differentiation could temporarily happen based on the message.

### Missing Visual

There should be an icon visible. The icon must be the same that's used by the Incident History. [Scroll down for details](https://github.com/Icinga/icinga-notifications-web/issues/157#issuecomment-1926996620)

### Incorrect Title

*acknowledged* is only the default phrase. For each type of event a new phrase should be added. At the moment, the phrase is identified based on the event severity. Since the severity was previously only missing for *Acknowledge* events sent by Icinga, the same phrase is used for internal events as well.

### Incorrect Source Icon

Internal events have no source, the icon is only shown because they are tied to objects still and such have a source. The source icon must reflect that they are internal events emitted by icinga-notifications. There's no icon or logo for this yet. @flourish86 may have input on this.

## Event Detail
![image](https://github.com/Icinga/icinga-notifications-web/assets/16668527/421dc44f-a142-48d6-af7a-2dda53e9ad2e)

### Incorrect Header

Once the visualization in the events listing is changed, this should be automatically reflected here.

### Missing Incident

This is an issue in icinga-notifications, as there's no entry in the `incident_event` table for internal events: https://github.com/Icinga/icinga-notifications/issues/151

### Source

This is again the source of the related object. The icon used should be the same as in the events listing for internal events and the label should just be *Icinga Notifications*.

## Incident History
![image](https://github.com/Icinga/icinga-notifications-web/assets/16668527/a7ef515c-f310-4a4f-a8d8-d40c66eaf68a)

### Object Name

The name of the object is redundant and doesn't need to be repeated on every severity change. Must be removed.

### Visuals

Should use the new icons mentioned [below](https://github.com/Icinga/icinga-notifications-web/issues/157#issuecomment-1926996620).

### Content

At the moment, source events are not shown. Only incident events. ~~This should be extended so that source events are also visible, so that if a source event is listed, the incident events caused by it appear chronologically afterwards. (Yes, this means that the first severity!=ok event is the first, and incident opened the second.)~~

~~The list can grow very large, if an incident is open for a long time. We should limit the history shown in the detail to a definite number of rows. (e.g. 15) All history entries should only be listed in a separate tab which works the same as host/service history tabs in Icinga DB Web.~~

**Comment by flourish86** [comment]
I listed the icons for the internal events here.

![Frame 8](https://github.com/Icinga/icinga-notifications-web/assets/6977434/64f2b93a-0e80-4fa3-b4b1-c09ebd3095aa)

Also the internal events' appearance should be different from the status changes. In this example I made the external events' icons a little bigger. Please also note that the status icon shapes are contained in the FontAwesome icon glyphs, while the internal event visuals have a circular element applied on them.

![Incident History List](https://github.com/Icinga/icinga-notifications-web/assets/6977434/fe34548c-3ab7-49cc-9e32-f79a2eb85c92)

Let me know, if you need css details for the updated styles.

**Comment by flourish86** [comment]
The message phrases are also not very user-friendly and could be improved visually and writing-wise.

Here are some suggestions, that could be discussed.

![Frame 18](https://github.com/Icinga/icinga-notifications-web/assets/6977434/c31bd6ca-8acb-4aee-8ab0-87cc30453c47)

![Frame 19](https://github.com/Icinga/icinga-notifications-web/assets/6977434/03ae16b4-5b1e-4fc8-a5f3-de5fcc743bba)

more to come …

**Comment by nilmerg** [comment]
Linking the recipient is currently questionable. We have no dedicated detail view, only a configuration form in case of contacts, and that is out of scope for this issue.

**Comment by ncosta-ic** [comment]
> ### Incorrect Source Icon
> 
> Internal events have no source, the icon is only shown because they are tied to objects still and such have a source. The source icon must reflect that they are internal events emitted by icinga-notifications. There's no icon or logo for this yet. @flourish86 may have input on this.

I currently render internal entries on the event list like the following:
![external_vs_internal](https://github.com/Icinga/icinga-notifications-web/assets/146938323/5ac8cf5a-aacf-4127-88b3-7cd239876155)

@flourish86 Did you already come up with a design idea, on how we should differentiate events that are tied to a source (showing the source icon next to the "0m 00s ago") and ones that are _not_ tied to a source (like in my example above where I placed a text placeholder)?

**Comment by ncosta-ic** [comment]
> > ### Incorrect Source Icon
> > Internal events have no source, the icon is only shown because they are tied to objects still and such have a source. The source icon must reflect that they are internal events emitted by icinga-notifications. There's no icon or logo for this yet. @flourish86 may have input on this.
> @flourish86 Did you already come up with a design idea, on how we should differentiate events that are tied to a source (showing the source icon next to the "0m 00s ago") and ones that are _not_ tied to a source (like in my example above where I placed a text placeholder)?

It was decided to drop the source information on internal events altogether, since they don't originate from an actual data source.
