### ISSUE TITLE
Contactgroup Configuration

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-notifications-web#174]
## Goal

We need a way to configure contactgroups in the UI.

## How it Should Work

* A tab in the `Configuration` menu section should lead to a list of contactgroups
* This list allows to paginate, limit, sort, search for and create contactgroups
* The button to create a contactgroup should be on the top left of the list
  * Clicking on it, opens a modal which allows to choose a name and define the group's members by using a `TermInput`
  * Saving closes the modal and shows the group's detail in the right column
* A click on a list item opens up a detail on the right, showing the name of the group in the header
  * A button on the name's right side allows to edit it
  * The modal should be the same as when creating a group, plus a remove button
* The detail's content lists a group's members, clicking on such an item leads to the contact's configuration view

**Comment by ncosta-ic** [comment]
I might consider updating the ContactGroup class once https://github.com/Icinga/icinga-notifications/issues/187 gets sorted out.
It currently links to the `contactgroup` table and this implies a class name of `Contactgroup`, which seems wrong.
