### ISSUE TITLE
Support new event types

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-notifications-web#215]
The `type` column of the `event` table now has a defined type which only allows certain values:

- acknowledgement-cleared
- acknowledgement-set
- custom
- downtime-end
- downtime-removed
- downtime-start
- flapping-end
- flapping-start
- incident-age (previously internal)
- state

Previously only the following values where used:

- state
- internal (now incident-age)

We need to support the new values, remove all workarounds (`internal` support, message matching) and show proper phrases:

Type | Phrase
-------|-----------
acknowledgement-cleared | was unacknowledged
acknowledgement-set | has been acknowledged
custom | _no phrase needed_
downtime-end | left a downtime period
downtime-removed | prematurely left a downtime period
downtime-start | entered a downtime period
flapping-end | left a flapping period
flapping-start | entered a flapping period
incident-age | exceeded **a** time constraint
state | _depending on severity, unchanged_

**Comment by yhabteab** [comment]
There are also two new event types (`mute`, `unmute`) since https://github.com/Icinga/icinga-notifications/pull/200.

**Comment by nilmerg** [comment]
This is a very different change. A separate issue will follow.

**Comment by yhabteab** [comment]
They are not that different, at least in regard to the event table. These two events are also part of the `event.type` enum.
