### ISSUE TITLE
Desktop notifications daemon default listen address

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications-web#239]
The [documentation](https://icinga.com/docs/icinga-notifications-web/latest/doc/06-Desktop-Notifications/#configure-the-daemon) states `host = [::]` as the default (which also matches the behavior I observed when testing the packages). However, the next section then says "you need to configure your web server to proxy requests to the daemon" which makes me question if the default shouldn't be to just listen on localhost and only expose it using the proxying web server.

**Comment by nilmerg** [comment]
Agreed. I've also never been a fan of the default port: 9001

Do you have a suggestion here as well?

**Comment by julianbrost** [comment]
Not for TCP, I'd prefer Unix domain sockets (which would have the positive side effect of not needing a port), but from what I remember, that can be annoying to get working with the Apache httpd.

**Comment by nilmerg** [comment]
Chose 5664 as default port. @oxzi suggested this because if you look at some port listing, it shows up together with Icinga 2.
