### ISSUE TITLE
Improvement suggestions for the desktop notifications documentation

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications-web#240]
While testing the packages, it would have helped if the documentation states which additional Apache http modules are required. With Icinga Web 2 already running on a otherwise blank Debian 12 system, I additionally had to enable the following three modules using `a2enmod` to get that config snippet working: `headers`, `proxy`, `proxy_http`

Additionally, a hint that working HTTPS is required for that feature should not hurt either.

**Comment by nilmerg** [comment]
> it would have helped if the documentation states which additional Apache http modules are required.

Agreed.

> a hint that working HTTPS is required for that feature should not hurt either.

That's already there:

> A user can enable this feature in their account preferences, in case Icinga Web is being accessed by using a secure connection.

**Comment by julianbrost** [comment]
> > a hint that working HTTPS is required for that feature should not hurt either.
> 
> That's already there:
> 
> > A user can enable this feature in their account preferences, in case Icinga Web is being accessed by using a secure connection.

Ah, I was only searching for "HTTPS" on the page to see if I overlooked anything :sweat_smile:
